### ISSUE TITLE
 Could NOT find NUMA (missing: NUMA_LIBRARY NUMA_INCLUDE_DIR)

### ISSUE THREAD

**Issue by ztdepztdep** [ginkgo-project/ginkgo#1000]
How to resolve this problem?

**Comment by upsj** [comment]
There are two things you can do: Either install `libnuma` (this might depend on your environment, something like `apt install libnuma-dev` or the equivalent for your package manager), or disable the compilation of the hwloc support or the compilation of tests (since that's the only thing we use libnuma for) by setting `GINKGO_BUILD_HWLOC` or `GINKGO_BUILD_TESTS` to `OFF` in your CMake configuration.

**Comment by upsj** [comment]
Hi @ztdepztdep, were you able to resolve the issues with `libnuma`? Then I will close this issue soon, otherwise please let us know what other issues you encountered.
