### ISSUE TITLE
How to play with examples

### ISSUE THREAD

**Issue by gfcas** [ginkgo-project/ginkgo#1078]
Maybe I missed it, but I have a suggestion to the examples: Can somewhere in the frist examples stated how to build and execute the examples? There are some build.sh scripts, but one can also give arguments like the executor for example ``./simple-solver "omp"``, if it is correct. This would make it easier for any new students without large programming knowledge to play with the tutorials.

**Comment by xwentian2020** [comment]
There is an option GINKGO_BUILD_EXAMPLES, and its default value is `ON`. After building the code, there will be a directory named examples in the build directory, where the built results (or executable binary files) are kept. Before running these files, export a certain environment variable(s) for the sake of performance or device selection. 
I also agree with you that a few individual examples should be provided for learning how to use the derived Ginkgo libraries in real applications and to build the code, because existing examples are built along with the Ginkgo libraries.
