### ISSUE TITLE
Check if MPI and OpenMP were already found in CMake

### ISSUE THREAD

**Issue by lahwaacz** [ginkgo-project/ginkgo#1096]
CMake's FindMPI and FindOpenMP have issues when `CMAKE_EXECUTABLE_SUFFIX` is not empty, see https://gitlab.kitware.com/cmake/cmake/-/issues/23874

That's why we find the packages before setting `CMAKE_EXECUTABLE_SUFFIX` in our main CMakeLists.txt:
```
find_package( OpenMP COMPONENTS CXX )
find_package( MPI COMPONENTS CXX )

# Settings for debug build
if( CMAKE_BUILD_TYPE STREQUAL "Debug")
    set( CMAKE_EXECUTABLE_SUFFIX "-dbg${CMAKE_EXECUTABLE_SUFFIX}" )  # suffix for executables
    set( CMAKE_DEBUG_POSTFIX "-dbg" )  # suffix for libraries
endif()
```

Now if we later on want to find Ginkgo (e.g. in a subdirectory for a specific target/module), we get the problem again, because Ginkgo's CMake file does `find_package(OpenMP)` and `find_package(MPI)` again. Instead, you could check the `OPENMP_FOUND` and `MPI_FOUND` variables to avoid our issue and also overhead.

**Comment by upsj** [comment]
IMO this is an upstream issue that we shouldn't attempt to fix/workaround ourselves. OPENMP_FOUND being set from the outside doesn't mean find_package ran through successfully, we need to be able to rely on such properties. If you want to set an executable suffix, I would recommend setting it on your own targets, not globally. As a workaround, you can empty and reset the variable around `add_subdirectory(ginkgo)`.

Also, I would recommend avoiding `if(CMAKE_BUILD_TYPE STREQUAL "...")`, since it breaks with multi-config generators.

**Comment by lahwaacz** [comment]
We use `find_package(Ginkgo)` so it shouldn't be set on any foreign targets. I agree that this is 100% CMake issue...

On second thought, checking `OPENMP_FOUND` and `MPI_FOUND` does not make sense because it might be a result of finding different `COMPONENTS`.
