### ISSUE TITLE
Improved kernel mapping

### ISSUE THREAD

**Issue by gflegar** [ginkgo-project/ginkgo#177]
Currently we map the kernels to executors with [`GKO_REGISTER_OPERATION`](https://github.com/ginkgo-project/ginkgo/blob/develop/core/base/executor.hpp#L264). There might be a better way to implement this functionality by [_inheriting from lambdas_](https://www.youtube.com/watch?v=W-xTpqj31mI).

**Comment by upsj** [comment]
Material:
[Inheriting from lambdas](https://www.youtube.com/watch?v=W-xTpqj31mI)
[Relevant SO question](https://stackoverflow.com/questions/7870498/using-declaration-in-variadic-template)

**Comment by upsj** [comment]
When talking to @MarcelKoch about the Ginkgo design, the topic of the complexity of GKO_REGISTER_OPERATION came up, since there, we are basically building a custom C++ closure instead of relying on things like lambdas to provide them for us.
Another approach might be using a named LambdaOperation to implement these steps, which somewhat goes into the same direction?
```cpp
template <typename Args...>
make_spmv(Args&&... args) {
    return LambdaOperation<...>{
        [&](gko::kernels::omp::spmv(std::forward<Args>(args)...);),
        [&](gko::kernels::cuda::spmv(std::forward<Args>(args)...);),
        [&](gko::kernels::hip::spmv(std::forward<Args>(args)...);));
]
```
The main difference this makes is that it captures the arguments once for each executor, instead of just once in general, which the `std::tuple` in GKO_REGISTER_OPERATION takes care of. Maybe we should evaluate how much of a performance difference that makes for the kernels with the largest number of parameters?
