### ISSUE TITLE
Export CMake configuration variables for external libraries

### ISSUE THREAD

**Issue by pratikvn** [ginkgo-project/ginkgo#210]
We need to export relevant CMake variables/settings appropriately so that external libraries can use it as necessary.

For example, if ginkgo has been built with `-DBUILD_CUDA =on `, then an external library needs to be able to read somehow during its configuration that ginkgo has been built with cuda. 

@tcojean suggested using the `export` [function](https://cmake.org/cmake/help/latest/command/export.html). More details about package management [here](https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#package-configuration-file)

**Comment by tcojean** [comment]
@pratikvn `export` is so that you do not need a `FindGinkgo.cmake`. The purpose of that is that when you build ginkgo, it would be registered to the cmake package manager and become usable transparently. The other alternative is to install Ginkgo normally (system wide) in which case it is found directly by CMake. If Ginkgo is put in a custom user path, then it is required to append the path to the `GinkgoTargets.cmake` (and so on) in the `CMAKE_PREFIX_PATH` environment variable, after which CMake finds the installation properly. So in all cases, there should be no need for a `FindGinkgo.cmake`.

Next, the problem of passing those flags is another one. I have searched quite a bit in the documentation and online and I cannot see how to expose such variables properly to CMAKE for them to be exported and reused by other packages upon finding Ginkgo. The best and most proper case would be to do something to the `ginkgo_reference` (etc) targets to differentiate between "fake" and "real" libraries, but I cannot see what yet.

**Comment by tcojean** [comment]
I put a suggestion in PR #211. I'm not really happy with this solution but it should work nonetheless.
