### ISSUE TITLE
Provide tests or implementation for some applies to multiple RHS

### ISSUE THREAD

**Issue by tcojean** [ginkgo-project/ginkgo#253]
The following are the status of formats
1. have implementations and tests
    - coo, csr, dense, ell, hybrid, sellp on reference executor
    - coo, ell, sellp on cuda executor
    - dense on omp executor
2. have implementations but don't have tests
    - hybrid and dense on cuda executor
    - coo, csr, ell, sellp on omp executor
3. don't have implementations
    - csr on cuda executor

**Comment by thoasm** [comment]
@yhmtsai I saw that you already implemented all the missing OpenMP tests in #251 .
The last point is pretty important (being able to compute an SpMV with multiple RHS with CSR). Is it possible for you to work on that?

I could take care of the CUDA tests (which is probably looking at your OpenMP tests and changing small parts), but the CUDA CSR kernel is quite complex, and it would probably take quite some time to understand it good enough that I could add the multiple RHS support.

**Comment by yhmtsai** [comment]
@thoasm I am working on the cuda csr implementation, it is in the [this branch](https://github.com/yhmtsai/ginkgo/tree/cuda-mrhs-support)
I also finished other formats' tests on cuda.
For csr part
I will not implement multiple right hand side support of `cuSparse` because it can not handle the vector with stride.
`Classical` and `load_balance` are done. I also use `selection` for `merge_path`.
I will finish mrhs support of `merge_path` tomorrow.

**Comment by thoasm** [comment]
@yhmtsai Perfect, thank you very much!
