### ISSUE TITLE
hypre matrix format

### ISSUE THREAD

**Issue by hartwiganzt** [ginkgo-project/ginkgo#382]
With the intention to have a smoother interface to [hypre](https://computing.llnl.gov/projects/hypre-scalable-linear-solvers-multigrid-methods), it would be good to implement a matrix format composed of CSR + diag (this is how hypre stores matrices on a node). I see two options how to realize this: 

1. creating the new matrix format completely independent of what already exists
+ we keep the flat hierarchy 
+ we may design special kernels that avoid a two-kernel-call in the SpMV
- we run into the problem which Csr strategy to use

2. compose the new matrix format as combination of to existing formats (Csr  + Dense)
+ we can leaverage the distinct strategies of Csr SpMV already implemented
+ we have less code duplication
- we lose the flat hierarchy and it may get complicated with the different Csr strategies 

@tcojean @upsj @pratikvn @yhmtsai @thoasm, I welcome opinions!

**Comment by thoasm** [comment]
Is it just the diagonal, or kind of a band (for example 3 elements per row)?
Is it required that the diagonal is completely separated from the CSR matrix (I would assume so)?

Just a note for the Part 2.: We can't really use a plain Dense matrix here since storing the diagonal in dense would take as much storage as the whole matrix in dense. I assume you meant something like an Array, containing only the diagonal elements.

Since we will have a normal CSR matrix anyway, we can compose the new matrix format out of a CSR matrix and an Array containing the diagonal elements. That way, we don't have to reimplement the functionality of the CSR matrix, but we need to forward the corresponding calls. We should not use inheritance here, since it would not be [subtyping](https://en.wikipedia.org/wiki/Subtyping), which would likely confuse the user (since the new format is not just a CSR matrix).
That way, we can simply use the CSR strategies and kernels while adding one to handle the diagonal. However, we might want to hand-write a kernel for this specific format to get the best performance possible if we plan to use it in Ginkgo as well.

**Comment by pratikvn** [comment]
I looked through the code and it seems that they have a [serial CSR format](https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_matrix.h#L43) where they store where it looks like they store row pointers, col idxs and values normally as we do. Then for a [distributed matrix storage](https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/_hypre_parcsr_mv.h#L282), it looks like they do store the diagonal and off-diagonal entries separately but both in CSR format. So, even the diagonal elements are stored in the normal CSR fashion.

For example, this function [hypre_CSRMatrixToParCSRMatrix](https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_matrix.c#L1157) takes in a CSR matrix on one rank and distributes it to all ranks by first creating a normal `hypre_CSRMatrix` on each process after [sending it from root](https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_matrix.c#L1329), and then generates the separation of the diagonal and the off-diagonal elements storing both of them in CSR on each of the ranks, which is in the [`par_matrix` object](https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_matrix.c#L1183) which is of `hypre_ParCSRMatrix` type.


For the SpMV, atleast according to what I see, both the diagonal and the off-diagonal CSR matrices seem to be calling the same function, [hypre_CSRMatvecOutOfPlace](https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_matvec.c#L24), [for diagonal](https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_matvec.c#L275) and [off-diagonal](https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_matvec.c#L305).

So, I am not sure it will be efficient to have to store the diagonal elements as a CSR matrix as well ?

**Comment by hartwiganzt** [comment]
I discussed with the hypre team: Diag is not a diagonal matrix, but a CSR matrix that contains only local to the process connections whereas Offd contains the coefficients that connect to off processor rows. Think of a 1D matrix partitioning. So I guess it is just a combination of two CSR matrices, then.

**Comment by tcojean** [comment]
According to what you say then we do not have to do anything for hypre as in the end the local data is stored in a plain CSR format, and we do not do anything MPI related?

**Comment by klausbu** [comment]
When looking at the hypre format, have a look at petsc too, as they share the same data model as I understand it where each process gets two data sets in CSR format. A continuous block of rows is assigned to each process in from of TWO data sets in CSR format. One data set containing the elements of the diagonal block (n x n), the other data set containing the off-diagonal elements of the assigned block of rows to exploit MPI functionality for higher performance.

I think http://www.gaspils.de/ also uses a data model leveraging a continuous block of rows which is exploited in a different way - for inspiration.

**Comment by upsj** [comment]
@hartwiganzt I guess this is being addressed with the current distributed setup, so can we close it?

**Comment by hartwiganzt** [comment]
yes, I agree to close this issue.
