### ISSUE TITLE
Make the `Csr::automatical` strategy work with `gko::Executor`

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#425]
Currently, we need either a `HipExecutor` or a `CudaExecutor` to create the `Csr::automatical` strategy.
It would be a lot easier to have a constructor that just takes a `gko::Executor`, so we could use it with any executor.

One way of implementing that is to remove the constructors that take `HipExecutor` and `CudaExecutor` and replace it with one that just takes `Executor`, which uses `dynamic_cast` to check for CUDA and HIP executors, while also working for different executors.

However, this might break interface, so we have to discuss on that.

**Comment by upsj** [comment]
This is also slightly related to the "double-destroy" segfaults we had with #418, since the `automatical` strategy is default-constructed with a `CudaExecutor`

**Comment by tcojean** [comment]
The default `CudaExecutor` was here before, because automatical in the previous releases was purely a Cuda strategy. Changing this would definitely break interface. We can consider this a bugfix maybe and then justify that change.

On the other hand, the change proposed here should be fine, we would have the same constructor with the same parameters which should do the same thing as currently given the same argument.

**Comment by tcojean** [comment]
#969 implemented a non-interface breaking way of achieving the same result. But `Csr::automatical` and strategies in general still need to be fixed.

**Comment by upsj** [comment]
Sounds like the remaining work is covered by #320, I think this can be closed
