### ISSUE TITLE
Testing freezes in `gpu/test/preconditioner/block_jacobi_kernels` with Titan V

### ISSUE THREAD

**Issue by yhmtsai** [ginkgo-project/ginkgo#54]
The testing freezes in gpu/test/preconditioner/block_jacobi_kernels when using cuda 9.0 and cuda 9.1 with Titan V.

There are freezing testing cases in block_jacobi_kernels:
- BlockJacobi.GpuPreconditionerEquivalentToRefWithMPW.
- BlockJacobi.GpuApplyEquivalentToRef
- BlockJacobi.GpuLinearCombinationApplyEquivalentToRef
- BlockJacobi.GpuApplyToMultipleVectorsEquivalentToRef
- BlockJacobi.GpuLinearCombinationApplyToMultipleVectorsEquivalentToRef

Run these tests is fine when using cuda 8.0, cuda 9.0, and cuda 9.1 with K40, but they freeze when using cuda 9.0 and cuda 9.1 with Titan V

**Comment by gflegar** [comment]
Doesn't sound good... @hartwiganzt can we check this on ICL's V100 and see if the same thing happens, or the problem only happens with Titan V?

**Comment by hartwiganzt** [comment]
I have to confirm the problem for the V100.

**Comment by tcojean** [comment]
Great investigation Goran!

What was nvidia doing before Volta? They always got the wrong mask in those instructions, so they did not synchronize at all?

**Comment by upsj** [comment]
I ran into similar issues with my selection routine.
With Pascal and earlier architectures, no synchronization was necessary
since all threads had to execute exactly the same (as in "same
instruction address") *_sync routine with the same mask.
My guess would be that the mask was only used to filter out results from
unwanted branches (e.g., for ballot votes), but not for any real
synchronization.

With Volta, it is now possible to synchronize two different branches
that execute the same (as in "same instruction and mask") instruction.

Also, for future reference, on Pascal and earlier, __syncthreads needed
to be called from only one thread in a warp for the whole warp to be
synchronized. With Volta, this may lead to a deadlock.

For more details, also check out the documentation for compute capability 7:

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#independent-thread-scheduling-7-x

**Comment by gflegar** [comment]
Here is the continuation of my investigation.

Two available APIs
--------------------------

Since CUDA 9.0, there are two ways to use warp-level synchronization primitives:
1.  Using the low-level API (`__shfl_sync()` and co.).
2.  Using cooperative groups, which are implemented on top of the low-level API.

Here is an example of (sub-)warp reduction, implemented in both ways (note that it can be done a bit more efficiently using the xor version of shuffle, but that's not the issue here):

```c++
// cooperative groups:
template <typename Group>
__forceinline__ __device__ float group_reduce(const Group &g, float v) {
    #pragma unroll
    for (auto offset = g.size() / 2; offset >= 1; offset /= 2) {
        auto tmp = g.shfl_down(v, offset);
        if (g.thread_rank() < offset) {
            v += tmp;
        }
    }
    return g.shfl(v, 0);
}

// low-level API:
template <uint32 WarpSize>
__forceinline__ __device__ float low_level_reduce(
        uint32 mask, float v) {
    #pragma unroll
    for (auto offset = WarpSize / 2; offset >= 1; offset /= 2) {
        auto tmp = __shfl_down_sync(mask, v, offset, WarpSize);
        if ((threadIdx.x % WarpSize) < offset) {
            v += tmp;
        }
    }
    return __shfl_sync(mask, v, 0, WarpSize);
}
```

Calling the functions is also a bit different. Using the low-level API, we have to somehow compute the mask, while using cooperative groups, we do not have to do it, so it is much easier to call:

```c++
// cooperative groups
auto block = cg::this_thread_block();
auto tile = cg::tiled_partition<WarpSize>(block);
group_reduce(tile, local_value);

// low-level API
// assuming that the block configuration is (WarpSize, 32 / WarpSize, whatever)
auto mask = static_cast<uint32>(((1ul << WarpSize) - 1) << (threadIdx.y * WarpSize));
low_level_reduce<WarpSize>(mask, local_value);
```
With cooperative groups it's also not possible to pass the wrong mask (which can happen in the other version), as the group itself computes the mask. Another issue I already noticed in a lot of kernels are issues with launch configuration: notice that the kernel using the low-level API assumes that blockDim.x is a multiple of warp size, and this is in no way clearly communicated to the caller. With cooperative groups, this problem disappears. I was already thinking before about introducing a similar abstraction into Ginkgo, to deal with the issue we have now with a lot of device functions, where there is extensive documentation for each of them describing what the function assumes the launch configuration looks like.

Performance Considerations
--------------------------------------

Since cooperative groups are a higher-level API, the first question is whether the result is the same compiled code, or at least code that has the same performance as the low-level API.
The first thing I looked into is the implementation of cooperative groups in `<cuda-installation-folder>/include/cooperative_groups.h`. Basically, the `shfl` method looks like this:

```c++
    _CG_QUALIFIER unsigned int build_mask() const {
        unsigned int mask;

        if (numThreads == 32) {
            mask = 0xFFFFFFFF;
        }
        else {
            mask = (unsigned int)(-1) >> (32 - numThreads);
            mask <<= (__internal::laneid() & (~(numThreads - 1)));
        }
        return (mask);
    }

    _CG_QUALIFIER int shfl(int var, int srcRank) const {
        return (__shfl_sync(build_mask(), var, srcRank, numThreads));
    }
```

So `shfl` calls `build_mask()` every time it is invoked. Seems like it could be an issue, if the compiler cannot optimize it. I looked into the PTX generated for the two reduction examples above (compiled with `nvcc --ptx -arch=sm_70 example.cu`). Here is how a single iteration of the loop looks like:

```ptx
// cooperative groups
	shfl.sync.down.b32 	%r19|%p1, %r15, %r17, %r16, %r18;
	mov.b32 	 %f5, %r19;
	// inline asm
	mov.u32 %r5, %laneid;
	// inline asm
	and.b32  	%r20, %r5, 16;
	setp.lt.u32	%p2, %r20, 16;
	add.f32 	%f6, %f36, %f5;
	selp.f32	%f7, %f6, %f36, %p2;
	mov.b32 	 %r21, %f7;
	mov.u32 	%r22, 8;

// low-level API
	shfl.sync.down.b32 	%r12|%p1, %r9, %r11, %r10, %r2;
	mov.b32 	 %f5, %r12;
	add.f32 	%f6, %f69, %f5;
	setp.lt.u32	%p2, %r4, 16;
	selp.f32	%f7, %f6, %f69, %p2;
	mov.b32 	 %r13, %f7;
	mov.u32 	%r14, 8;
```

9 instructions / iteration for cooperative groups, versus 7 for low-level API. However, PTX is not the last stage of optimization, and there are some additional optimizations that the compiler does when converting PTX to binary. So I looked into the actually binary code (`nvcc -arch=sm_70 example.cu; cuobjdump -sass a.out`). It was quite difficult to get the kernel I wanted to test. Since I wanted to have multiple repetitions of the reduction (so the time needed is long enough to measure), I had to wrap everything into another loop. However, the compiler would then play "smart" and automatically unroll the outer loop, and do something fancy with the code inside the unrolled loop - so I was no longer testing the reduction multiple times, but multiple merged version of it (I had to explicitly tell it not to unroll the loop). Here is the full compiled kernel which does the reduction multiple times:

```
// low-level API
/*0000*/              @!PT SHFL.IDX PT, RZ, RZ, RZ, RZ ;
/*0010*/                   IMAD.MOV.U32 R1, RZ, RZ, c[0x0][0x28] ;
/*0020*/                   S2R R4, SR_TID.X ;
/*0030*/                   S2R R3, SR_TID.Y ;
/*0040*/                   IMAD.MOV.U32 R2, RZ, RZ, c[0x0][0x160] ;
/*0050*/                   ISETP.LT.AND P0, PT, R2, 0x1, PT ;
/*0060*/                   I2F.U32 R0, R4 ;
/*0070*/                   FADD R0, R0, 1 ;
/*0080*/               @P0 BRA 0x220 ;
/*0090*/                   LOP3.LUT R6, R4, 0x1f, RZ, 0xc0, !PT ;
/*00a0*/                   IMAD.MOV.U32 R5, RZ, RZ, -0x1 ;
/*00b0*/                   SHF.L.U32 R2, R3, 0x5, RZ ;
/*00c0*/                   ISETP.LT.U32.AND P0, PT, R6.reuse, 0x10, PT ;
/*00d0*/                   ISETP.LT.U32.AND P1, PT, R6.reuse, 0x8, PT ;
/*00e0*/                   ISETP.LT.U32.AND P2, PT, R6.reuse, 0x4, PT ;
/*00f0*/                   ISETP.LT.U32.AND P3, PT, R6, 0x2, PT ;
/*0100*/                   ISETP.EQ.AND P5, PT, R6, RZ, PT ;
/*0110*/                   SHF.L.U32 R6, R5, R2, RZ ;
/*0120*/                   MOV R2, RZ ;
/*0130*/                   IMAD.MOV.U32 R5, RZ, RZ, R0 ;                 <<<
/*0140*/                   SHFL.DOWN PT, R0, R5, 0x10, 0x1f ;
/*0150*/               @P0 FADD R5, R0, R5 ;
/*0160*/                   SHFL.DOWN PT, R0, R5, 0x8, 0x1f ;
/*0170*/               @P1 FADD R5, R5, R0 ;
/*0180*/                   SHFL.DOWN PT, R0, R5, 0x4, 0x1f ;
/*0190*/               @P2 FADD R5, R5, R0 ;
/*01a0*/                   SHFL.DOWN PT, R0, R5, 0x2, 0x1f ;
/*01b0*/               @P3 FADD R5, R5, R0 ;
/*01c0*/                   SHFL.DOWN PT, R0, R5, 0x1, 0x1f ;
/*01d0*/                   IADD3 R2, R2, 0x1, RZ ;
/*01e0*/                   ISETP.LT.AND P4, PT, R2, c[0x0][0x160], PT ;
/*01f0*/               @P5 FADD R5, R5, R0 ;
/*0200*/                   SHFL.IDX PT, R0, R5, RZ, 0x1f ;
/*0210*/               @P4 BRA 0x130 ;                                  <<<
/*0220*/                   ISETP.NE.AND P0, PT, R4, RZ, PT ;
/*0230*/               @P0 EXIT ;
/*0240*/                   S2R R2, SR_CTAID.X ;
/*0250*/                   MOV R4, 0x4 ;
/*0260*/                   IMAD R2, R2, c[0x0][0x4], R3 ;
/*0270*/                   IMAD.WIDE.U32 R2, R2, R4, c[0x0][0x168] ;
/*0280*/                   STG.E.SYS [R2], R0 ;
/*0290*/                   EXIT ;
/*02a0*/                   BRA 0x2a0;
/*02b0*/                   NOP;
/*02c0*/                   NOP;
/*02d0*/                   NOP;
/*02e0*/                   NOP;
/*02f0*/                   NOP;

// cooperative groups
/*0000*/              @!PT SHFL.IDX PT, RZ, RZ, RZ, RZ ;
/*0010*/                   IMAD.MOV.U32 R1, RZ, RZ, c[0x0][0x28] ;
/*0020*/                   S2R R3, SR_TID.X ;
/*0030*/                   IMAD.MOV.U32 R2, RZ, RZ, c[0x0][0x160] ;
/*0040*/                   ISETP.LT.AND P0, PT, R2, 0x1, PT ;
/*0050*/                   I2F.U32 R0, R3 ;
/*0060*/                   FADD R0, R0, 1 ;
/*0070*/               @P0 BRA 0x230 ;
/*0080*/                   S2R R2, SR_LANEID ;
/*0090*/                   LOP3.LUT R4, R2.reuse, 0x10, RZ, 0xc0, !PT ;
/*00a0*/                   LOP3.LUT R5, R2, 0x18, RZ, 0xc0, !PT ;
/*00b0*/                   ISETP.LT.U32.AND P0, PT, R4, 0x10, PT ;
/*00c0*/                   LOP3.LUT R6, R2.reuse, 0x1c, RZ, 0xc0, !PT ;
/*00d0*/                   LOP3.LUT R4, R2, 0x1e, RZ, 0xc0, !PT ;
/*00e0*/                   LOP3.LUT R2, R2, 0x1f, RZ, 0xc0, !PT ;
/*00f0*/                   ISETP.LT.U32.AND P1, PT, R5, 0x8, PT ;
/*0100*/                   ISETP.EQ.AND P5, PT, R2, RZ, PT ;
/*0110*/                   IMAD.MOV.U32 R2, RZ, RZ, RZ ;
/*0120*/                   ISETP.LT.U32.AND P2, PT, R6, 0x4, PT ;
/*0130*/                   ISETP.LT.U32.AND P3, PT, R4, 0x2, PT ;
/*0140*/                   IMAD.MOV.U32 R5, RZ, RZ, R0 ;                <<<
/*0150*/                   SHFL.DOWN PT, R0, R5, 0x10, 0x1f ;
/*0160*/               @P0 FADD R5, R0, R5 ;
/*0170*/                   SHFL.DOWN PT, R0, R5, 0x8, 0x1f ;
/*0180*/               @P1 FADD R5, R5, R0 ;
/*0190*/                   SHFL.DOWN PT, R0, R5, 0x4, 0x1f ;
/*01a0*/               @P2 FADD R5, R5, R0 ;
/*01b0*/                   SHFL.DOWN PT, R0, R5, 0x2, 0x1f ;
/*01c0*/               @P3 FADD R5, R5, R0 ;
/*01d0*/                   SHFL.DOWN PT, R0, R5, 0x1, 0x1f ;
/*01e0*/                   IADD3 R2, R2, 0x1, RZ ;
/*01f0*/                   ISETP.LT.AND P4, PT, R2, c[0x0][0x160], PT ;
/*0200*/               @P5 FADD R5, R5, R0 ;
/*0210*/                   SHFL.IDX PT, R0, R5, RZ, 0x1f ;
/*0220*/               @P4 BRA 0x140 ;                                  <<<
/*0230*/                   ISETP.NE.AND P0, PT, R3, RZ, PT ;
/*0240*/               @P0 EXIT ;
/*0250*/                   S2R R2, SR_TID.Y ;
/*0260*/                   S2R R3, SR_CTAID.X ;
/*0270*/                   IMAD.MOV.U32 R4, RZ, RZ, 0x4 ;
/*0280*/                   IMAD R2, R3, c[0x0][0x4], R2 ;
/*0290*/                   IMAD.WIDE.U32 R2, R2, R4, c[0x0][0x168] ;
/*02a0*/                   STG.E.SYS [R2], R0 ;
/*02b0*/                   EXIT ;
/*02c0*/                   BRA 0x2c0;
/*02d0*/                   NOP;
/*02e0*/                   NOP;
/*02f0*/                   NOP;
```

So, in fact, the resulting main loop is exactly the same, only the setup is done in a slightly different way.
Now what I cannot wrap my head around is that if I try to actually run this (1 warp, 1 block, multiple repetitions), I get no difference on V100, but cooperative groups work faster on P100 (I checked the code for sm_60 as well, the loops are again the same). How can the same code run faster in one case, and slower in the other? [Here](https://github.com/ginkgo-project/ginkgo/files/2392342/coop_group.cu.gz) is the code I used to test it, ff anyone sees something I might have missed that would explain it...


![image](https://user-images.githubusercontent.com/1261711/45682089-9dd33b00-bb3f-11e8-80ab-6e25cb6368cc.png)

![image](https://user-images.githubusercontent.com/1261711/45682810-be03f980-bb41-11e8-914c-5a60f8baa882.png)

So, it seems that from the performance perspective, there's no difference between the two APIs, and for some (for now) inexplicable reason, is even faster than using the low-level API...

Functionality
-----------------

In terms of functionality, cooperative groups do not exactly offer the same thing as the low-level API, and have some restrictions. For example, the size of the sub-warp has to be know at compile-time when using shuffles. This is not true for the low-level API, and the size can be a runtime argument. However, in most cases, we do actually know the sub-warp size at compile-time.  A more significant restriction is that cooperative groups do not allow arbitrary masks for warp cooperation primitives. Basically, the only masks supported are masks of entire subwarps, and the mask returned by `__activemask()`. I'm not sure why they didn't do the other ones. Seems to me like the same code for the activemask group should work for any other mask, but maybe I'm missing something.

However, a cooperative group is not actually a specific class, and doesn't have to inherit from some other class or anything. They are just a concept (like standard library's iterator for example), so we can easily define our own cooperative groups that have the same interface as the standard ones, and they will work just the same.

Availability
--------------

An additional problem with both of these things is that they are only available in CUDA 9+. So we either have to say we do not support older CUDA versions (FYI: CUDA 9 is now 1 year old), or we have to provide some compatibility layer for older CUDA versions (which means that there's more work for us to do).

**Comment by hartwiganzt** [comment]
So I do assume that the cooperative groups are what NVIDIA plans to push in future. Is that true? Then we should probably adopt it...

**Comment by gflegar** [comment]
I think it is, and it is definitely a better abstraction than using masks directly, so I would go with that.
The only question is what we do with older versions of CUDA? Just drop support?

**Comment by hartwiganzt** [comment]
drop support for the routines that need that feature.

**Comment by gflegar** [comment]
Easier said than done:

- this cannot be done automatically, there's additional compile-time
switches that have to be done to inform the user about it
- we have to document somewhere what is supported and what is not
- it's not always straightforward to figure out if a specific kernel is
supported or not, as it might not be using new features by itself, but only
depends on function that use them, we have to keep track of what each
device function uses
- it can cause developers to think twice before using a new feature, as
their kernel would not be supported on the system
- we would have to test Ginkgo on older versions of CUDA to make sure it
works as expected

And the benefit is enabling people that are to lazy to install a newer CUDA
version to use parts of Ginkgo.

I don't think it's worth it...

**Comment by hartwiganzt** [comment]
ok. let's require CUDA>=9.0
