### ISSUE TITLE
Examples Webpage

### ISSUE THREAD

**Issue by gfcas** [ginkgo-project/ginkgo#815]
Dear ginkgo developers,
I observed that there are some new examples (the three mixed precision ones), which are drawn in the example tree, however, dont show up in the example list? This time, before opening a new PR, I first ask about it :)

As a suggestion, maybe it would be nice to rearrange the example tree a bit, because it is very wide and I have to scroll horizontal.

**Comment by yhmtsai** [comment]
Hi @gfcas, 
Yes, you are right. we miss the example in the following list.
It is required to manually add the new items in the doc/examples/examples.hpp.in
I am not sure whether making automatically generation is easy or not.
Does @pratikvn have some idea about the example tree? I think it is generated by dot.

If you have idea and free time to fix it, please feel free to create a PR and we appreciate it.
or, we will fix it.

**Comment by gfcas** [comment]
I know it also from dealii, where I added my tutorial manually to the list of examples. Maybe a ordering would also be nice (like step/example-1, 2, 3, ...). Maybe I would try to find some time until next Monday.

**Comment by gfcas** [comment]
Does someone know if there is a ``make documentation`` target? At the first view wit ``make help`` I did not found one.

**Comment by upsj** [comment]
When you enable `GINKGO_BUILD_DOC`, you have the `usr` target, which generates user documentation. When you enable `GINKGO_DOC_GENERATE_DEV`, you additionally have the `dev` target, which generates developer documentation containing additional `@internal` parts of Ginkgo.

**Comment by pratikvn** [comment]
Yes, Currently the graph is generated from the list in examples.hpp.in using dot-graphviz. We could grep the list of examples and add it automatically, but it might not be necessary as we dont regularly keep adding examples, that it would get out of our control.

**Comment by upsj** [comment]
Another alternative would be moving to a different graphviz engine, e.g.
## circo
![file](https://user-images.githubusercontent.com/1693511/124476206-db61eb00-dda2-11eb-8286-8a3d90f09351.png)
## twopi
![file2](https://user-images.githubusercontent.com/1693511/124476312-f03e7e80-dda2-11eb-9595-d911b44876d6.png)
## fdp
![file3](https://user-images.githubusercontent.com/1693511/124476335-f7658c80-dda2-11eb-888e-32857e5f9971.png)
## neato
![file4](https://user-images.githubusercontent.com/1693511/124476363-ff253100-dda2-11eb-9617-3f9fe6bf8028.png)

or doing the layout by hand, which might not be that much of an overhead, since we only rarely add new nodes.

**Comment by yhmtsai** [comment]
I think the generation is handled by examples.pl.
can it add some fixed-width or fixed-number-per row?

**Comment by upsj** [comment]
![examples](https://user-images.githubusercontent.com/1693511/124477241-131d6280-dda4-11eb-831f-5663f8b46cdb.png)
Here is a quick example put together using yEd. The issue with trying to compress this to a more narrow drawing is that this will obscure the structure of the graph even more. We should probably clean up our transitive dependencies a bit.

**Comment by gfcas** [comment]
> Here is a quick example put together using yEd (looks like edge directionality got lost in the conversion, though). The issue with trying to compress this to a more narrow drawing is that this will obscure the structure of the graph even more. We should probably clean up our transitive dependencies a bit.

Maybe if you have a tutorial story like 1,2,3,... (Sorry, maybe you notice that I grew up with dealii :) )

**Comment by upsj** [comment]
That's perfectly fine, the thing with Ginkgo is that we would probably have multiple stories to tell instead of a single storyline, so the graph definitely makes sense. We do need to clean up our edges, though!

**Comment by pratikvn** [comment]
To me, atleast currently while the graph is slightly wide and does not fit in a page, it should be okay, because you easily drag the graph. The idea of the graph was to give a quick idea of the dependencies, show the main example categories and show all the available examples in a visual form. The graph is also meant to showcase the complexities of the examples, in that the examples at the top are supposed to implement simple examples, and the ones at the bottom, are more complicated features.

I am not sure about numbers, because as Tobias mentioned we dont have a clear path like deal.ii, where you have a proper story to tell.

**Comment by gfcas** [comment]
> 
> 
> When you enable `GINKGO_BUILD_DOC`, you have the `usr` target, which generates user documentation. When you enable `GINKGO_DOC_GENERATE_DEV`, you additionally have the `dev` target, which generates developer documentation containing additional `@internal` parts of Ginkgo.

Thanks! ``usr`` was the target I was looking for :)

**Comment by gfcas** [comment]
> I am not sure about numbers, because as Tobias mentioned we dont have a clear path like deal.ii, where you have a proper story to tell.

Yeah, then we probabely let it in the current state. Less work :)

**Comment by gfcas** [comment]
Does someone wants to assign PR #819 with this issue such that it gets closed automatically?
