### ISSUE TITLE
Improve random matrix generation

### ISSUE THREAD

**Issue by pratikvn** [ginkgo-project/ginkgo#862]
Currently, our random matrix generation is slow for even relatively medium sizes because we allocate a fully dense matrix data object and then fill values randomly into it. 

It might be useful to allocate and fill only sparse matrix data when generating the sparse matrix formats.

**Comment by upsj** [comment]
I think that's only true for the matrix_data constructor, not for the one used in the tests. We could still improve that one, since it shuffles a vector of all column indices for each row. For a small number of nonzeros compared to the number of columns, it would be more efficient to pick random indices and remove duplicates.

**Comment by pratikvn** [comment]
I believe we only have one main `generate_random_matrix` function and that is implemented in `core/test/utils/matrix_generator.hpp`. Yes, we need to update the matrix_data object to only allocate the non-zero entries and not rely on that constructor

**Comment by upsj** [comment]
Yes, that one is sparse and mainly has performance limitations due to the aforementioned column shuffle. Do we have some tests where this causes performance issues?

**Comment by pratikvn** [comment]
Not yet. I was trying to generate some random matrices to experiment with and I found that this generation was slow. I think it should be easy to fix this and make this faster so that we can use it as a fast way to experiment with different types of matrices. In the long term, of course we should probably have some proper sparse matrix generation.
