### ISSUE TITLE
Ginkgo configuration options

### ISSUE THREAD

**Issue by gfcas** [ginkgo-project/ginkgo#873]
Sorry guys, this is more a question than an issue: Looking into the CMakeLists.txt file I found the two options
```
GINKGO_MIXED_PRECISION
GINKGO_JACOBI_FULL_OPTIMIZATIONS
```
I suppose they are advanced options? What are the basic benefit of them, should the be enabled to get the best performance?

**Comment by pratikvn** [comment]
GKO_MIXED_PRECISION is a CMake option that allows you to compile true mixed-precision kernels instead of converting data on the fly. The default is OFF. Enabling this flag increases the library size, but improves performance of mixed-precision kernels. 

GKO_JACOBI_FULL_OPTIMIZATIONS is to use all the optimizations for the CUDA Jacobi algorithm. OFF by default. Setting this option to ON may lead to very slow compile time (>20 minutes) for the jacobi_generate_kernels.cu file and high memory usage.

So these options are only for certain algorithms and if you are looking for high-performance for these algorithms, then you may try to enable these. If you are not using these algorithms, then switching them off is recommended.

**Comment by gfcas** [comment]
OK, so if compile time and memory does not matter this options increas the performance. Many thanks!
