### ISSUE TITLE
newbie question about the input json array of `benchmark/solver/solver`

### ISSUE THREAD

**Issue by zhf-0** [ginkgo-project/ginkgo#992]
Hello, after I installed ginkgo, I used the program `/benchmark/solver/solver` to verify the installation was right. But I could not get results by the following commands 
```bash
./solver -executor cuda "[{ "filename": "/data/ssget/HB/1138_bus/1138_bus.mtx", "optimal": { "spmv": "csr" } } ]"
```
By the way, the matrix `1138_bus.mtx` is from suitesparse matrix collection. The output was 
```bash
This is Ginkgo 1.4.0 (master)
    running with core module 1.4.0 (master)
    the reference module is  1.4.0 (master)
    the OpenMP    module is  1.4.0 (master)
    the CUDA      module is  1.4.0 (master)
    the HIP       module is  not compiled
    the DPCPP     module is  not compiled
Running on cuda(0)
Running with 2 warm iterations and 1 running iterations
The random seed for right hand sides is 42
Running cg with 1000 iterations and residual goal of 1.000000e-06
The number of right hand sides is 1
``` 
and the program hung up without any information.

I looked up the source code `solver.cpp` which said 
> Input has to be a JSON array of matrix configurations

I used
```bash
./solver -executor cuda "[{ "filename": "/data/ssget/HB/1138_bus/1138_bus.mtx", "optimal": { "spmv": "csr" } } ]"
./solver -executor cuda [{ "filename": "/data/ssget/HB/1138_bus/1138_bus.mtx", "optimal": { "spmv": "csr" } } ]
```
but neither was right. So, which is the right way to write json array?

**Comment by upsj** [comment]
Hi @zhf-0, you have it almost right. There are two details you need to consider:
1. string escaping: some of the characters in your input have special meaning in bash, so you need to make sure they are interpreted as strings. so instead of `[{ "filename": "...", ... } ]`, I usually do `'[{ "filename":"...", ... }]'` - notice the single quotes around the JSON. I use single quotes, because then you don't have any interaction with the double quotes " from the JSON itself.
2. Ginkgo takes the input not via commandline, but via stdin, i.e. you need to pipe the input into the benchmark tool, either via pipe or via input redirect from a file
```bash
echo '[{"filename":"..."}]' | benchmark/solver/solver -solvers gmres,cg -executor cuda
benchmark/solver/solver -solvers gmres,cg -executor cuda < input.json
```
Benchmarks print status messages to stderr and their final output to stdout, so you can also redirect the output like `> output.json` or use `-backup output.json` to store the benchmark results.

**Comment by zhf-0** [comment]
Thank you very much! Ginkgo is a terrific job. By the way, is there any plan about `-executor mpi` in the future?

**Comment by upsj** [comment]
Yes, that is currently under development, see #907 for tracking. It will not be an executor though, since the executor model does not match the requirements of distributed computing well, but instead build on top of our current setup via dedicated distributed matrix and vector types.

**Comment by zhf-0** [comment]
I'm looking forward to its coming.
